run:
  deadline: 5m
  tests: true
  modules-download-mode: vendor
  skip-dirs:
  - vendor
  build-tags: []

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
  - revive
  - errcheck
  - misspell
  - deadcode
  - govet
  - typecheck
  - lll
  - megacheck
  - varcheck
  - unconvert
  - bodyclose
  - exportloopref
  - goimports
  - ineffassign
  - gofmt
  - goconst
  - gocyclo
  - unparam
  - structcheck
  - staticcheck
  - gocritic

linters-settings:
  govet:
    check-shadowing: true
    enable:
    - atomicalign
    - assign
    - atomic
    - bools
    - buildtag
    - cgocall
    - composites
    - copylocks
    - errorsas
    - framepointer
    - httpresponse
    - ifaceassert
    - loopclosure
    - lostcancel
    - nilfunc
    - printf
    - shift
    - stdmethods
    - stringintconv
    - structtag
    - testinggoroutine
    - unmarshal
    - tests
    - unreachable
    - unsafeptr
    - unusedresult
  misspell:
    locale: US
  unused:
    check-exported: false
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: arhat.dev/renovate-server
  lll:
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 4

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - dupl
    - gosec
    - maligned
    - lll
    - scopelint

  - text: "commentFormatting: put a space between `//` and comment text"
    linters:
    - gocritic
